version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: nghia3092003
      MYSQL_DATABASE: loginbaomatweb
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    networks:
      - app-network

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge